### ISSUE TITLE
How to use in Arduino IDE? 

### ISSUE THREAD

**Issue by Pillar1989** [raspberrypi/pico-examples#1]
Please support the Arduino IDE development environment.

**Comment by aallan** [comment]
Arduino is releasing their [own RP2040-based board](https://blog.arduino.cc/2021/01/20/welcome-raspberry-pi-to-the-world-of-microcontrollers/). That means they'll be porting the Arduino Development Environment to the RP2040. When they do you'll be able to run it on Raspberry Pi Pico.
