### ISSUE TITLE
Pico parallel pio

### ISSUE THREAD

**Issue by siriokds** [raspberrypi/pico-examples#105]
Can PIO state machines read/write 8+ pins at time? If not, is there available any tip to handle this?
Thanks.

**Comment by lurch** [comment]
Looks like this can be done with the `IN` instruction, with `PINS` as the source? Just set the `Bit count` to the number of pins you need to read?
(and similarly with `OUT` for writing pins)

**Comment by siriokds** [comment]
> Looks like this can be done with the `IN` instruction, with `PINS` as the source? Just set the `Bit count` to the number of pins you need to read?
> (and similarly with `OUT` for writing pins)

So I can read/write or change pin direction of 32 pins at once. Did I get it right?

**Comment by lurch** [comment]
I believe so, yes (although there's only 26 GPIO pins available on Raspberry Pi Pico).

**Comment by siriokds** [comment]
> I believe so, yes (although there's only 26 GPIO pins available on Raspberry Pi Pico).

Thank you.
