### ISSUE TITLE
pio blink example incorrect frequency

### ISSUE THREAD

**Issue by smist09** [raspberrypi/pico-examples#108]
The line in the C program is:

    pio->txf[sm] = clock_get_hz(clk_sys) / 2 * freq;

Should be:

    pio->txf[sm] = clock_get_hz(clk_sys) / freq;

**Comment by lurch** [comment]
Fixed by #121

**Comment by lurch** [comment]
This should probably be closed too @kilograham ?

**Comment by kilograham** [comment]
closes as duplicate (which has also been merged)
