### ISSUE TITLE
TinyUSB Host example code is broken

### ISSUE THREAD

**Issue by csBlueChip** [raspberrypi/pico-examples#156]
Attempts to build the USB Host HID example code fails. 

Apparently because of a couple of missing macros.
* CFG_TUH_HID
* HID_KEYCODE_TO_ASCII

...and a couple of undefined types
* hid_keyboard_report_t
* hid_mouse_report_t

(Full output below)

Also reported here:
* https://www.raspberrypi.org/forums/viewtopic.php?t=306856
* https://www.raspberrypi.org/forums/viewtopic.php?t=312374

Start with a clean pull of the sdk and example code:
* pull pico-sdk
* pull submodules (tinyusb)
* pull pico-examples

``` shell
mkdir ~/build
cd ~/build
cmake /path/to/examples
    ...
    TinyUSB available at /home/pico/pico-sdk/lib/tinyusb/src/portable/raspberrypi/rp2040; adding USB support.
    ...
```

``` c
cd usb/host/host_hid/
make
    ...
    ...

Scanning dependencies of target host_hid
[  0%] Building C object usb/host/host_hid/CMakeFiles/host_hid.dir/host_hid.c.obj
In file included from /home/pico/pico-sdk/lib/tinyusb/src/host/usbh.h:38:0,
                 from /home/pico/pico-sdk/lib/tinyusb/src/tusb.h:43,
                 from /home/pico/pico-sdk/lib/tinyusb/hw/bsp/board.h:42,
                 from /home/pico/pico-examples/usb/host/host_hid/host_hid.c:30:
/home/pico/pico-sdk/lib/tinyusb/src/host/hcd.h:87:62: error: 'CFG_TUH_HID' undeclared here (not in a function); did you mean 'CFG_TUD_HID'?
   HCD_MAX_ENDPOINT = CFG_TUSB_HOST_DEVICE_MAX*(CFG_TUH_HUB + CFG_TUH_HID*2 + CFG_TUH_MSC*2 + CFG_TUH_CDC*3),
                                                              ^~~~~~~~~~~
                                                              CFG_TUD_HID
/home/pico/pico-examples/usb/host/host_hid/host_hid.c:61:29: error: unknown type name 'hid_keyboard_report_t'
 CFG_TUSB_MEM_SECTION static hid_keyboard_report_t usb_keyboard_report;
                             ^~~~~~~~~~~~~~~~~~~~~
/home/pico/pico-examples/usb/host/host_hid/host_hid.c:62:40: error: 'HID_KEYCODE_TO_ASCII' undeclared here (not in a function)
 uint8_t const keycode2ascii[128][2] = {HID_KEYCODE_TO_ASCII};
                                        ^~~~~~~~~~~~~~~~~~~~
/home/pico/pico-examples/usb/host/host_hid/host_hid.c:65:39: error: unknown type name 'hid_keyboard_report_t'
 static inline bool find_key_in_report(hid_keyboard_report_t const *p_report, uint8_t keycode) {
                                       ^~~~~~~~~~~~~~~~~~~~~
/home/pico/pico-examples/usb/host/host_hid/host_hid.c:73:39: error: unknown type name 'hid_keyboard_report_t'
 static inline void process_kbd_report(hid_keyboard_report_t const *p_new_report) {
                                       ^~~~~~~~~~~~~~~~~~~~~
/home/pico/pico-examples/usb/host/host_hid/host_hid.c: In function 'tuh_hid_keyboard_mounted_cb':
/home/pico/pico-examples/usb/host/host_hid/host_hid.c:102:5: warning: implicit declaration of function 'tuh_hid_keyboard_get_report'; did you mean 'tuh_hid_keyboard_mounted_cb'? [-Wimplicit-function-declaration]
     tuh_hid_keyboard_get_report(dev_addr, &usb_keyboard_report);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
     tuh_hid_keyboard_mounted_cb
/home/pico/pico-examples/usb/host/host_hid/host_hid.c: At top level:
/home/pico/pico-examples/usb/host/host_hid/host_hid.c:120:29: error: unknown type name 'hid_mouse_report_t'
 CFG_TUSB_MEM_SECTION static hid_mouse_report_t usb_mouse_report;
                             ^~~~~~~~~~~~~~~~~~
/home/pico/pico-examples/usb/host/host_hid/host_hid.c:145:41: error: unknown type name 'hid_mouse_report_t'
 static inline void process_mouse_report(hid_mouse_report_t const *p_report) {
                                         ^~~~~~~~~~~~~~~~~~
/home/pico/pico-examples/usb/host/host_hid/host_hid.c: In function 'hid_task':
/home/pico/pico-examples/usb/host/host_hid/host_hid.c:185:9: warning: implicit declaration of function 'tuh_hid_keyboard_is_mounted'; did you mean 'tuh_hid_keyboard_unmounted_cb'? [-Wimplicit-function-declaration]
     if (tuh_hid_keyboard_is_mounted(addr)) {
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
         tuh_hid_keyboard_unmounted_cb
/home/pico/pico-examples/usb/host/host_hid/host_hid.c:186:14: warning: implicit declaration of function 'tuh_hid_keyboard_is_busy'; did you mean 'tuh_hid_keyboard_isr'? [-Wimplicit-function-declaration]
         if (!tuh_hid_keyboard_is_busy(addr)) {
              ^~~~~~~~~~~~~~~~~~~~~~~~
              tuh_hid_keyboard_isr
/home/pico/pico-examples/usb/host/host_hid/host_hid.c:187:13: warning: implicit declaration of function 'process_kbd_report' [-Wimplicit-function-declaration]
             process_kbd_report(&usb_keyboard_report);
             ^~~~~~~~~~~~~~~~~~
/home/pico/pico-examples/usb/host/host_hid/host_hid.c:194:9: warning: implicit declaration of function 'tuh_hid_mouse_is_mounted'; did you mean 'tuh_hid_mouse_unmounted_cb'? [-Wimplicit-function-declaration]
     if (tuh_hid_mouse_is_mounted(addr)) {
         ^~~~~~~~~~~~~~~~~~~~~~~~
         tuh_hid_mouse_unmounted_cb
/home/pico/pico-examples/usb/host/host_hid/host_hid.c:195:14: warning: implicit declaration of function 'tuh_hid_mouse_is_busy'; did you mean 'tuh_hid_mouse_isr'? [-Wimplicit-function-declaration]
         if (!tuh_hid_mouse_is_busy(addr)) {
              ^~~~~~~~~~~~~~~~~~~~~
              tuh_hid_mouse_isr
/home/pico/pico-examples/usb/host/host_hid/host_hid.c:196:13: warning: implicit declaration of function 'process_mouse_report' [-Wimplicit-function-declaration]
             process_mouse_report(&usb_mouse_report);
             ^~~~~~~~~~~~~~~~~~~~
/home/pico/pico-examples/usb/host/host_hid/host_hid.c:197:13: warning: implicit declaration of function 'tuh_hid_mouse_get_report'; did you mean 'tuh_hid_mouse_isr'? [-Wimplicit-function-declaration]
             tuh_hid_mouse_get_report(addr, &usb_mouse_report);
             ^~~~~~~~~~~~~~~~~~~~~~~~
             tuh_hid_mouse_isr
make[2]: *** [usb/host/host_hid/CMakeFiles/host_hid.dir/build.make:63: usb/host/host_hid/CMakeFiles/host_hid.dir/host_hid.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:6467: usb/host/host_hid/CMakeFiles/host_hid.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

I'm utterly lost in a rabbit warren of code and CMakeLists ...Any help to get this going in the short-term would be gratefully appreciated.

Would anybody know the git commands required to pull an old version of the sdk/examples/tinyusb when (I assume) it used to work?

Happy to put in a pull request if I can fix it properly.

BC

**Comment by bl4krat** [comment]
github.com/raspberrypi/tinyusb != github.com/hathach/tinyusb

It looks like the guy at raspberry forked the hathach/tinyusb repo into rasbperrypi/tinyusb and haven't maintained it for about 7 months. Unfortunately, <THAT> repo has the broken usb host code - and even mentions the same in the documents.

Meanwhile, work has continued on hathach's (ie, the original / 'official'?) repo. The host code was last updated only a few days ago with raspberry rp2040 updates.

Also unfortunately, the pico-sdk appears to submodule their own fork, not the hathach one....

Today I pulled down the hathach/tinyusb repo and compiled their host example - hid_controller  (dead easy: 'make BOARD=raspberry_pi_pico') and it compiled me a .uf2 out of the box so now I can plug usb HID devices into a pico and see the vIDs & pIDs appear in minicom.

**Comment by csBlueChip** [comment]
Thank you @kilograham and @bl4krat .

My original issue is now resolved.
* update examples to remove USB code
* pull the hathach version of TinyUSB
* compile the hathach hid_controller example with<br/>`mkdir ~/test ; cd ~/test`<br/>`cmake -DFAMILY=rp2040 /path/to/tinyusb/examples/host/hid_controller/`<br/>`make`

I'd like to add two footnotes to this resolution (which may be of use to others finding this thread in the future):
* I wonder if the SDK should either a) update its submodule list to use a working USB stack, or b) just stop including a broken library ...including known-broken code in the official sdk is very misleading.
* Please note that [at the time of writing this] if you compile the hid_controller example with "debug" enabled <br/>`cmake -DFAMILY=rp2040 -DCMAKE_BUILD_TYPE=Debug /path/to/tinyusb/examples/host/hid_controller/`<br/>you will get an assertion failure when you connect a device<br/>`assertion "ep->active" failed: file "/path/to/tinyusb/src/portable/raspberrypi/rp2040/hcd_rp2040.c", line 164, function: hw_trans_complete`<br/>...Obviously, this needs to be addressed properly at some point, but a quick'n'dirty work around is just to comment out the assert - and things (seemingly) will work as expected!?

**Comment by kilograham** [comment]
> github.com/raspberrypi/tinyusb != github.com/hathach/tinyusb
> 
> It looks like the guy at raspberry forked the hathach/tinyusb repo into rasbperrypi/tinyusb and haven't maintained it for about 7 months. Unfortunately, repo has the broken usb host code - and even mentions the same in the documents.
> 
originally the SDK used a fork, yes... hasn't in a while

> Meanwhile, work has continued on hathach's (ie, the original / 'official'?) repo. The host code was last updated only a few days ago with raspberry rp2040 updates.
> 
> Also unfortunately, the pico-sdk appears to submodule their own fork, not the hathach one....
> 
untrue. https://github.com/raspberrypi/pico-sdk/blob/bfcbefafc5d2a210551a4d9d80b4303d4ae0adf7/.gitmodules#L3

you probably baven't synced your submodules properly.

> Today I pulled down the hathach/tinyusb repo and compiled their host example - hid_controller (dead easy: 'make BOARD=raspberry_pi_pico') and it compiled me a .uf2 out of the box so now I can plug usb HID devices into a pico and see the vIDs & pIDs appear in minicom.

yes... the TinyUSB examples now build directly from TinyUSB (or pico_examples)

**Comment by kilograham** [comment]
> Please note that [at the time of writing this] if you compile the hid_controller example with "debug" enabled
cmake -DFAMILY=rp2040 -DCMAKE_BUILD_TYPE=Debug /path/to/tinyusb/examples/host/hid_controller/
you will get an assertion failure when you connect a device
assertion "ep->active" failed: file "/path/to/tinyusb/src/portable/raspberrypi/rp2040/hcd_rp2040.c", line 164, function: hw_trans_complete
...Obviously, this needs to be addressed properly at some point, but a quick'n'dirty work around is just to comment out the assert - and things (seemingly) will work as expected!?

please report this against TinyUSB

**Comment by kilograham** [comment]
`git submodule sync` is perhaps what some people are missing

**Comment by bl4krat** [comment]
The instructions in "Getting started with raspberry pi pico" (paragraph 2.1) say:

Then clone the pico-sdk and pico-examples git repositories.
$ git clone -b master https://github.com/raspberrypi/pico-sdk.git
$ cd pico-sdk
$ git submodule update --init

if you do that, you see:

Submodule 'tinyusb' (https://github.com/hathach/tinyusb.git) registered for path 'lib/tinyusb'
Cloning into '/home/pico/pico-sdk/lib/tinyusb'...
Submodule path 'lib/tinyusb': checked out 'd49938d0f5052bce70e55c652b657c0a6a7e84fe'

So it DOES LOOK for all the world like it is updating from the hathatch (original) repo, I grant you.

BUT, take a look at the files you ACTUALLY have in pico-sdk/lib/tinyusb after that...

README.md (not README.rst)
CONTRIBUTORS.md (not CONTRIBUTORS.rst)
CODE_OF_CONDUCT.md (not CODE_OF_CONDUCT.rst)
tinyusb.Doxyfile (but no .readthedocs.yaml)

examples/host contains no hid_controller folder.

etc......

Whatever it is doing, it is NOT pulling in the up-to-date hathach/tinyusb repo and sticking it in lib/tinyusb

**Comment by lurch** [comment]
> Submodule 'tinyusb' (https://github.com/hathach/tinyusb.git) registered for path 'lib/tinyusb'
Cloning into '/home/pico/pico-sdk/lib/tinyusb'...
Submodule path 'lib/tinyusb': checked out 'd49938d0f5052bce70e55c652b657c0a6a7e84fe'
> 
> So it DOES LOOK for all the world like it is updating from the hathatch (original) repo, I grant you.

Uh-huh...

> BUT, take a look at the files you ACTUALLY have in pico-sdk/lib/tinyusb after that...
>
> README.md (not README.rst)
CONTRIBUTORS.md (not CONTRIBUTORS.rst)
CODE_OF_CONDUCT.md (not CODE_OF_CONDUCT.rst)
tinyusb.Doxyfile (but no .readthedocs.yaml)
>
> examples/host contains no hid_controller folder.

...yup, and that matches the state of the `hathach/tinyusb` repo at commit-id `d49938d0f5052bce70e55c652b657c0a6a7e84fe`
https://github.com/hathach/tinyusb/tree/d49938d0f5052bce70e55c652b657c0a6a7e84fe

> Whatever it is doing, it is NOT pulling in the up-to-date hathach/tinyusb repo and sticking it in lib/tinyusb

Correct - git submodules only point at a specific commit-ID not at the "up to date version" - this way the "parent repo" knows exactly what versions of the files it'll get from the "submodule repo". (which prevents any future changes in the "submodule repo" from breaking the build of the "parent repo")

If you wanted to update your `hathach/tinyusb` submodule to the latest version, you need to do:
```bash
git submodule update --remote lib/tinyusb
```

but note that this updates `lib/tinyusb` to a newer version than that "officially supported" by `pico-sdk`, so any build failures are at your own risk.
