### ISSUE TITLE
Add SPI interrupt examples

### ISSUE THREAD

**Issue by wh201906** [raspberrypi/pico-examples#174]
Hi there. Could you please add some examples about how to use interrupt when communicating with SPI? The SDK doesn't provide related functions and I think this feature is common when using a MCU.

**Comment by lurch** [comment]
Does anything in #101 help? :man_shrugging:

**Comment by wh201906** [comment]
The spi_master_slave example seems to be polling the result rather than use the interrupt.
I know how to use the receive FIFO interrupt now. However, the interrupt is generated when the FIFO is half-full(maybe), so I cannot always get the latest data.
I have a time-sensitive task running with the DMA. So I don't want the DMA to be shared. In this case, how can I get the SPI data in real-time? 
Thank you for any help you can provide.

**Comment by lurch** [comment]
I dunno much about SPI, but I've just had a skim through section "4.4. SPI" of https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf and yeah it does seem like you only get a receive interrupt if the receive FIFO becomes half-full, and it seems that unlike the UART you can't adjust the FIFO depth; so maybe your only option is to poll `SSPSR.RNE` if you need to read data as soon as it arrives? :shrug:  (I guess you could even do that polling on the second core, and then send an interrupt to the first core?)
Or perhaps you could use the PIO implementation of SPI? https://github.com/raspberrypi/pico-examples/tree/master/pio/spi (although that might be master-only - see #104 and #115 )

**Comment by wh201906** [comment]
Polling with the second core might be a good solution for me. Thanks!
Should I close the issue now?
