### ISSUE TITLE
Picowifi.py

### ISSUE THREAD

**Issue by ph1lj-6321** [raspberrypi/pico-examples#184]
When I upload this example to the pico connected to the esp, i get back 

Traceback (most recent call last):
  File "<stdin>", line 45, in <module>
AttributeError: 'NoneType' object has no attribute 'decode'

which is referring to 
dat = buf.decode('UTF-8')				# Decode

Any ideas ?

**Comment by lurch** [comment]
That looks like a Python error, so you'll probably need to ask for help at https://forum.micropython.org/
