### ISSUE TITLE
One way of dealing with an issue

### ISSUE THREAD

**Issue by ph1lj-6321** [raspberrypi/pico-examples#185]
buf = uart.readline()					# Read data
dat = buf.decode('UTF-8')				# Decode

returns UnicodeError - 

I asked help  :-

I get told to contact MicroPython, yet on the book cover you say your code is "tried and tested" and then the question is closed

**Comment by aallan** [comment]
This repo is C example code to accompany the C/C++ SDK for RP2040. I'm not sure what book are you talking about?

**Comment by ph1lj-6321** [comment]
I'm looking at the Raspberry Pi Pico Essentials - Dogan Ibrahim

**Comment by ph1lj-6321** [comment]
I think I'm in the wrong site - thanks anyway

**Comment by aallan** [comment]
That isn't a book we're responsible for, sorry. Not heard of it.
