### ISSUE TITLE
fritzing schematic wrong for oled i2c example

### ISSUE THREAD

**Issue by ImmanuelH** [raspberrypi/pico-examples#191]
The image of the fritzing schematic for oled i2c example (pico-examples/i2c/oled_i2c/oled_i2c_bb.png) is wrong. 
All connections are off by one. I have not checked is this also applies to the fritzing schematic itself.

**Comment by lurch** [comment]
Thanks, see #194

**Comment by kilograham** [comment]
merged into develop
