### ISSUE TITLE
links to pico_w-examples in README.MD are not working

### ISSUE THREAD

**Issue by jumjum123** [raspberrypi/pico-examples#228]
For example
https://github.com/raspberrypi/pico-examples/blob/master/pico_w/picow_wifi_scan
gives 404 error

https://github.com/raspberrypi/pico-examples/tree/master/pico_w/wifi_scan
or
https://github.com/raspberrypi/pico-examples/blob/master/pico_w/wifi_scan
both work fine

**Comment by aallan** [comment]
Happy to take a PR?
