### ISSUE TITLE
Add sd card on spi or sdio example

### ISSUE THREAD

**Issue by rmeshpresh** [raspberrypi/pico-examples#239]
Please add sd card on spi or sdio example. As it is basic requirements for many projects.

**Comment by lurch** [comment]
See `pico_sd_card` in https://github.com/raspberrypi/pico-extras
(And see also https://github.com/raspberrypi/pico-sdk/issues/531 )

**Comment by rmeshpresh** [comment]
Yes, but its still in testing phase it think. Please release in Pico - example after testing.
