### ISSUE TITLE
pico-spi sending

### ISSUE THREAD

**Issue by qombajn** [raspberrypi/pico-examples#248]
Hello!
I want to run PGA2311U with Raspberry Pi Pico and I don't know how to setup spi:

uint8_t r=50;
uint8_t l=150;
spi_init(spi0,6250000); //6.25Mhz
gpio_set_function(PIN_MISO, GPIO_FUNC_SPI);
gpio_set_function(PIN_SCK, GPIO_FUNC_SPI);
gpio_set_function(PIN_MOSI, GPIO_FUNC_SPI);
gpio_set_function(PGA_CS, GPIO_FUNC_SPI);
spi_set_format(spi0,8,SPI_CPOL_0,SPI_CPHA_0,SPI_MSB_FIRST);
printf("spi try send  %d %d\n",r,l);
gpio_put(PGA_CS,0);
spi_write_blocking(spi0,&r,1);
spi_write_blocking(spi0,&l,1);
gpio_put(PGA_CS,1);

I don't know what is wrong in here. :( 
Here is PGA2311U Datasheet:
 [https://www.ti.com/lit/ds/symlink/pga2311.pdf?ts=1658994595000&ref_url=https%253A%252F%252Fwww.google.com%252F](url)
<img width="481" alt="1" src="https://user-images.githubusercontent.com/73279527/181452161-bea5667c-c5e0-4684-b1df-022375c50970.png">
<img width="513" alt="2" src="https://user-images.githubusercontent.com/73279527/181452167-2c648ab7-b4ce-4e62-badf-3782b9eb2b18.png">
<img width="961" alt="3" src="https://user-images.githubusercontent.com/73279527/181452172-867964a6-b0de-4946-a375-66bae83a9a71.png">

**Comment by lurch** [comment]
This is probably the sort of question better suited for https://forums.raspberrypi.com/viewforum.php?f=143

**Comment by qombajn** [comment]
Problem was bad wiring GND.
