### ISSUE TITLE
pico w examples do not get built

### ISSUE THREAD

**Issue by tiborh** [raspberrypi/pico-examples#260]
good up to this point:
1. create build directory (mkdir build)
2. cd build
3. cmake ..
4. then other make examples seem to be ok (e.g. hello_world or blink)
5. however make in picow directory does not build anything
any idea? what logs would be needed to make sure what is wrong?

**Comment by kilograham** [comment]
`cmake -DBOARD=pico_w ..` 

It does not actually log anything, perhaps it could (just seemed like spam for people who weren't using pico_w)

**Comment by tiborh** [comment]
great, thanks.
two new lines appeared:
```
Enabling build support for Pico W wireless.
Skipping some Pico W examples as WIFI_SSID is not defined
```

**Comment by kilograham** [comment]
https://datasheets.raspberrypi.com/picow/connecting-to-the-internet-with-pico-w.pdf

**Comment by tiborh** [comment]
Thank you. This is also great. A good second after the starter guide.

**Comment by efzedvi** [comment]
The freeRTOS examples however do not get built, as stated here:
https://github.com/raspberrypi/pico-examples/issues/251

**Comment by lurch** [comment]
@tiborh Can this be closed now?

**Comment by tiborh** [comment]
oh. yes. sorry. issue solved.
