### ISSUE TITLE
Add a test for mDns

### ISSUE THREAD

**Issue by peterharperuk** [raspberrypi/pico-examples#272]
I don't fully understand mDns but I think it gives me the ability to register a local domain name, so a web server can register and you can surf to it like http://picow1a28.local/?

Anyway - there's code in the SDK wrapped in #if LWIP_MDNS_RESPONDER, so we should test it works?

**Comment by lurch** [comment]
It seems like that's the `#if` that will cause https://github.com/georgerobotics/cyw43-driver/issues/17 to fall over?

**Comment by lurch** [comment]
I guess this should be closed, now that mDNS has been removed by https://github.com/georgerobotics/cyw43-driver/pull/39 ?

**Comment by peterharperuk** [comment]
It was removed from the driver, but I was going to add it to one of the examples.

**Comment by lurch** [comment]
Ah, apologies for my misunderstanding. So this will get fixed by #269 ?

**Comment by peterharperuk** [comment]
Yes - let me check if it works now.

**Comment by kilograham** [comment]
merged into develop

**Comment by kilograham** [comment]
actually - @peterharperuk is this fixed?

**Comment by peterharperuk** [comment]
I'm going to say yes (I just tested it). The httpd example you just pushed uses it. It prints out the host name...
mdns host name PicoW7282.local
If you are on the same subnet opening PicoW7282.local in a web browser takes you to the website. That's my understanding of mDNS.
