### ISSUE TITLE
Can we use WIFI_SSID and WIFI_PASSWORD from the environment?

### ISSUE THREAD

**Issue by peterharperuk** [raspberrypi/pico-examples#273]
We use some environment variables from the environment if they're not specified. But not WIFI_SSID and WIFI_PASSWORD. Can we do this to save some typing?

**Comment by kilograham** [comment]
sounds reasonable... i was gonna suggest changing the names (for the env vars), but i think this is fine as is

**Comment by kilograham** [comment]
merged into develop
