### ISSUE TITLE
pico-examples/pio/logic_analyser not working for some values of CAPTURE_PIN_COUNT

### ISSUE THREAD

**Issue by cmoulang** [raspberrypi/pico-examples#29]
The logic analyser example does not work when CAPTURE_PIN_COUNT does not divide exactly into 32. This is at odds with the comment in the file logic_analyser.c: "`// 1 to 32 pins can be captured.`"

For example: CAPTURE_PIN_COUNT=4 produces the following *correct* output:

`16: ----____________----____________----____________----____________----____________----____________`
`17: ------------____------------____------------____------------____------------____------------____`
`18: ________________________________________________________________________________________________`
`19: ________________________________________________________________________________________________`

However, with CAPTURE_PIN_COUNT=3 the output is:

`16: -----------____________________------------___________________------------___________________---`
`17: _______________----__------____-______________----___-----____--_____________----____----____---`
`18: ---_______-____------___________--____________-------___________-____________--------___________`

This is incorrect - the trace for pins 16,17 and 18 should be identical to the previous example.

The comment could be updated to state that "`// 1,2,4,8,16 or 32 pins can be captured.`" Alternatively the attached file contains a fix that works for all values from 1 to 32. 

Change summary: 
- The underlying issue is that the PIO discards bits when a sample overruns the available space in the ISR. To prevent this, `push_threshold` is set to a multiple of `pin_count`.
- The `capture_buf` size calculation has been updated.
- Calculation of the word and bit offsets in `print_capture_buf()` updated.

[logic_analyser.c.txt](https://github.com/raspberrypi/pico-examples/files/5910657/logic_analyser.c.txt)

**Comment by Wren6991** [comment]
Fixed, thank you!

**Comment by cmoulang** [comment]
Great! Thanks!
