### ISSUE TITLE
OpenOCD: GDB Server Quit Unexpectedly. VSCode and picoprobe

### ISSUE THREAD

**Issue by Navarro-Franco** [raspberrypi/pico-examples#291]
Greetings, 
I have a problem when I try to debug in VSCode with picoprobe. I copy the files from IDE/VSCode and I notice that I need to put   "runToEntryPoint": "main" instead of "RunToMain". But the problem persist so I cannot find what I'm missing.  It is possible that de documentation is obsolete in the part of "Chapter 7. Using Visual Studio Code" . My main OS is Arch but I tried with Ubuntu and I had the same problem.

This is the output when I try to debug. 

`Cortex-Debug: VSCode debugger extension version 1.6.7 git(b0f5563). Usage info: https://github.com/Marus/cortex-debug#usage
Reading symbols from arm-none-eabi-objdump --syms -C -h -w /home/navarro/software/pico/my_project_picos/console_w/build/console.elf
Reading symbols from arm-none-eabi-nm --defined-only -S -l -C -p /home/navarro/software/pico/my_project_picos/console_w/build/console.elf
Launching GDB: arm-none-eabi-gdb -q --interpreter=mi2
1-gdb-version
Launching gdb-server: /home/navarro/software/pico/openocd/src/openocd -c "gdb_port 50000" -c "tcl_port 50001" -c "telnet_port 50002" -s /home/navarro/software/pico/openocd/tcl -f /home/navarro/.vscode/extensions/marus25.cortex-debug-1.6.7/support/openocd-helpers.tcl -f interface/picoprobe.cfg -f target/rp2040.cfg
    Please check TERMINAL tab (gdb-server) for output from /home/navarro/software/pico/openocd/src/openocd
Finished reading symbols from objdump: Time: 24 ms
Finished reading symbols from nm: Time: 33 ms
OpenOCD: GDB Server Quit Unexpectedly. See gdb-server output in TERMINAL tab for more details.`

This is my settings.json

{
    // These settings tweaks to the cmake plugin will ensure
    // that you debug using cortex-debug instead of trying to launch
    // a Pico binary on the host
    "cmake.statusbar.advanced": {
        "debug": {
            "visibility": "hidden"
        },
        "launch": {
            "visibility": "hidden"
        },
        "build": {
            "visibility": "default"
        },
        "buildTarget": {
            "visibility": "hidden"
        }
    },
    "cmake.buildBeforeRun": true,
    "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools",
    "cortex-debug.openocdPath": "/home/navarro/software/pico/openocd/src/openocd",
    "cortex-debug.gdbPath": "arm-none-eabi-gdb",

}

and this is my lunch.json

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Pico Debug",
            "cwd": "${workspaceRoot}",
            "executable": "${command:cmake.launchTargetPath}",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "openocd",
            // This may need to be arm-none-eabi-gdb depending on your system
            "gdbPath" : "arm-none-eabi-gdb",
            "device": "RP2040",
            "configFiles": [
                "interface/picoprobe.cfg",
                "target/rp2040.cfg"
            ],
            "svdFile": "${env:PICO_SDK_PATH}/src/rp2040/hardware_regs/rp2040.svd",
            "runToEntryPoint": "main",
            // Work around for stopping at main on restart
            "postRestartCommands": [
                "break main",
                "continue"
            ],
            "searchDir": ["/home/navarro/software/pico/openocd/tcl"],
            "showDevDebugOutput": "parsed"
        }
    ]
}

**Comment by lurch** [comment]
Possibly related to https://github.com/raspberrypi/picoprobe/issues/49#issuecomment-1331748165 which says that the documentation and `launch.json` will be getting updated soon? ping @P33M
