### ISSUE TITLE
Tinyusb mass storage example

### ISSUE THREAD

**Issue by mandar1jn** [raspberrypi/pico-examples#301]
It'd be very useful if there was a port of https://github.com/hathach/tinyusb/tree/master/examples/device/cdc_msc to the pico. I've tried my hands at it but never managed to get close. I don't have headers so I have no real way to debug

**Comment by brendena** [comment]
If the raspberry pi pico foundation decides not to add this example.  I have a relatively easy project that uses MSC class that you might find helpful.  

https://github.com/brendena/pico_drag_n_drop_programmer

**Comment by kilograham** [comment]
all the TinyUSB examples are already built by pico-examples
