### ISSUE TITLE
this errors when adding mbedtls with pico sdk 

### ISSUE THREAD

**Issue by Shivdoke39** [raspberrypi/pico-examples#303]
![WhatsApp Image 2022-12-21 at 4 31 27 PM](https://user-images.githubusercontent.com/99238345/208890165-fb056e99-3635-44dc-a3b4-b25876c274eb.jpeg)

**Comment by peterharperuk** [comment]
Did you try the hint? run "git submodule update  --init"

**Comment by Shivdoke39** [comment]
fine...its working now.......but how  i get sample websocket tls client example after building?

**Comment by Shivdoke39** [comment]
Rebuild the sdk, then link your code to pico_lwip_mbedtls and
pico_mbedtls. See tls_client example in pico-examples???????????

**Comment by peterharperuk** [comment]
Please post questions in the forum. There's an example here https://github.com/peterharperuk/pico-examples/commit/450a4d51ae1dd5f571e06c636b1fda1ba80f6ace
