### ISSUE TITLE
ping example app throws lwip assert

### ISSUE THREAD

**Issue by peterharperuk** [raspberrypi/pico-examples#308]
The sys version.

**Comment by lurch** [comment]
Was this fixed by #309 ?

**Comment by peterharperuk** [comment]
> Was this fixed by https://github.com/raspberrypi/pico-examples/pull/309 ?

That was the intention?

**Comment by lurch** [comment]
Sorry, I meant if it has been fixed by a PR that has been merged, then perhaps this open issue can be closed? (purely for the sake of "tidiness")
Apologies if I came across as annoying, and there's actually a reason you're keeping this open...
