### ISSUE TITLE
pi pico integer division wrong using div_u64u64()

### ISSUE THREAD

**Issue by fbd-ss** [raspberrypi/pico-examples#310]
pwm_clock_freq = 1000000
target_usecs = 7092
var d comes out at 2797 instead of 7092

static inline uint32_t period_from_usec( uint32_t pwm_clock_freq, uint32_t target_usecs ) {
    uint64_t top = target_usecs * 1000000;
    auto d = div_u64u64( top, static_cast<uint64_t>( pwm_clock_freq ) );
    return ( target_usecs * 1000000 ) / pwm_clock_freq;
}

any ideas?

**Comment by kilograham** [comment]
because

```
target_usecs * 1000000;
```

is a 32 bit multiply; use `1000000ull`
