### ISSUE TITLE
sending commands through usb to uart

### ISSUE THREAD

**Issue by Noor-H** [raspberrypi/pico-examples#342]
Hi,
I want to interface SIM800L GSM module with Raspberry Pi Pico on uart1. I want to send commands via usb com port and the sim800l, attached on uart1 TX: 8, RX:9, will be sending response. I am trying to do [this](https://github.com/ahmadlogs/rpi-pico-arduino-ide/blob/main/rip-pico-sim800l/rip-pico-sim800l.ino) but using C SDK on pico. However I can't figure out the uart communication. I want to use both usb and uart at the same time but cannot. Is there any help available?

**Comment by aallan** [comment]
The "hello world" examples show you how to do both serial UART and USB serial, see https://github.com/raspberrypi/pico-examples/tree/master/hello_world. Probably the best place to get support for your project is on the [forums](https://www.raspberrypi.org/forums/),  but please follow up with further comments if you have specific questions about the example code.
