### ISSUE TITLE
picow_bt_example_freertos.c: mysterious include

### ISSUE THREAD

**Issue by dantor** [raspberrypi/pico-examples#373]
Hello,

in the bluetooth examples (freertos variant) the common file picow_bt_example_freertos.c includes a header called `"pico/btstack_init.h"`. However, I cannot find this file anywhere, nor does it seem to be necessary to build the examples successfully. Maybe this include can just be removed?

**Comment by peterharperuk** [comment]
Yes, well spotted. That was a last minute change before we released BT. I'll remove it.

**Comment by kilograham** [comment]
merged into develop
