### ISSUE TITLE
PIO / WS2812 ... Bug on preprocessor debug disable?

### ISSUE THREAD

**Issue by henrygab** [raspberrypi/pico-examples#41]
https://github.com/raspberrypi/pico-examples/blob/33854562cd08398c4b48bb1ed7fa022c2177076d/pio/ws2812/ws2812_parallel.c#L285-L291

First, I'm at a loss trying to understand why this is ever disabled, given that the PICO has dedicated SWD pins.  This also isn't checking against `PICO_DEFAULT_UART_TX_PIN`, `PICO_DEFAULT_UART_RX_PIN`, or `PICO_DEFAULT_LED_PIN` ... was it leftover from the FPGA days?

Even if it's OK for the non-parallel, however, it's not correct for this file, since it outputs to 2 consecutive GPIO.  `PIN_TX` is only the *first* GPIO that the state machines will push output through.  Therefore, if `PIN_TX` is defined as `2`, then it would still call `gpio_debug_pins_init()`, even though GPIO2 and GPIO3 would be getting DMA...

Thoughts appreciated?

**Comment by lurch** [comment]
I suspect this _may_ be timing debug-code that was left in by accident, similar to https://github.com/raspberrypi/pico-sdk/issues/28 ?

**Comment by henrygab** [comment]
Yep, that seems essentially the same.  :)  Please mark as duplicate or close, as per your preference!

**Comment by lurch** [comment]
IMHO this _isn't_ a duplicate, because it's affecting a different source-file than was being discussed in https://github.com/raspberrypi/pico-sdk/issues/28

**Comment by henrygab** [comment]
**You're right**.  The linked issue said it'd be going through all source, and [SDK commit #31](https://github.com/raspberrypi/pico-sdk/pull/31) closed #28.

My mistake was two-fold:
1. The linked issue said it would fix all the samples
2. I failed to realize that the linked issue was in a different depot

So, **_yes_**, this issue should remain alive in this depot, to either:
1. remove all instances of `CU_REGISTER_DEBUG_PINS()`, `CU_SELECT_DEBUG_PINS()`, `DEBUG_PINS_xxx`, etc.;  **_OR_**
2. comment out at least the `CU_REGISTER_DEBUG_PINS()`, `CU_SELECT_DEBUG_PINS()` lines

**Comment by lurch** [comment]
@kilograham For your consideration...

**Comment by kilograham** [comment]
just delete the debug pins stufff

**Comment by lurch** [comment]
Fancy submitting a PR to the `develop` branch @henrygab ?

**Comment by henrygab** [comment]
OK, see PR #47.

**Comment by henrygab** [comment]
Manually closing because I failed to properly link the PR.  :)
