### ISSUE TITLE
Problem connecting WebUSB example

### ISSUE THREAD

**Issue by nickzoic** [raspberrypi/pico-examples#42]
**Set up**

 - **PC OS**   : Ubuntu 20.04.1 
 - **Board**   : RPi Pico 
 - **Firmware**: examples/device/webusb_serial/ , pretty much.
 - **Compiler**: arm-none-eabi-gcc (15:9-2019-q4-0ubuntu1) 9.2.1 20191025 (release)

**Describe the bug**

When power the device up, the little Chrome notification opens saying "TinyUSB Device detected. Go to www.tinyusb.org to connect.".

When I click on that the device panics with message:

```
*** PANIC ***

ep %d %s was already available
``` 
emitted from the UART.  (If CFG_TUSB_DEBUG is set, it instead prints `ep 0 in was already available`, see below)

**To reproduce**

I've created a minimal project at `https://github.com/nickzoic/rpi-pico-webusb-example.git`
Sorry for the slightly complicated build, there's no `hw/bsp/raspberry_pi_pico/board.mk` file and I'm not sure how to make one.

1. Check it out (recursively) and build it with `make`
2. Upload `firmware.uf2` to board
3. Click on popup to connect Chrome to https://www.tinyusb.org/examples/webusb-serial/
4. :-( panic message on UART
5. Chrome shows message "NetworkError: Unable to set device interface."

Same thing happens if I ignore the popup message and use the 'Connect' button on the webusb-serial page to connect.

Interestingly, if I comment out that panic() call in `pico-sdk/lib/tinyusb/src/portable/raspberrypi/rp2040/rp2040_usb.c`, everything seems to work perfectly.

**Screenshots**

Here's a wireshark capture of the device, although I've got to admit the details are a bit beyond me: I hope this is the right thing!

[webusb.pcapng.gz](https://github.com/raspberrypi/tinyusb/files/5929830/webusb.pcapng.gz)

**Log**

[debug-uart.txt](https://github.com/raspberrypi/tinyusb/files/5929875/debug-uart.txt)

**Comment by kilograham** [comment]
this example is now gone
