### ISSUE TITLE
[Question] Basic gatt ble server on Pico W

### ISSUE THREAD

**Issue by thewh1teagle** [raspberrypi/pico-examples#454]
I'm trying to find basic example of gatt ble server on Pico W with two way communication for single client.
can you point me to the right one?
Also, the pico-w/bt folder looks pretty empty. most of the folders have only CMakeLists.txt, why?

Also when I try to build the standalone example from bt folder I get the error:
```
Unknown CMake command "pico_btstack_make_gatt_header".
```

There's no instructions how to use the bluetooth stack beyond to simply compile the example in this repo which I don't even know where is the c files

**Comment by lurch** [comment]
> Also, the pico-w/bt folder looks pretty empty. most of the folders have only CMakeLists.txt, why?

As it says at https://github.com/raspberrypi/pico-examples/blob/master/README.md#pico-w-bluetooth
"They are examples from the Blue Kitchen Bluetooth stack, see [here](https://bluekitchen-gmbh.com/btstack/#examples/examples/index.html) for a full description."
And looking at https://github.com/raspberrypi/pico-examples/blob/master/pico_w/bt/CMakeLists.txt it seems like it pulls in the BT examples from `${PICO_SDK_PATH}/lib/btstack/example/`.

(I'm afraid I can't provide help myself with your other questions, as I know almost nothing about Bluetooth)

**Comment by sonnny** [comment]
I have several ble examples (some might even have youtube demo) at below github link, source files are provided, there's even a bluetooth classic (not ble).

[https://github.com/sonnny](https://github.com/sonnny)

**Comment by peterharperuk** [comment]
try pico-examples\pico_w\bt\standalone
