### ISSUE TITLE
Make sure there's an example of using stdio_set_chars_available_callback

### ISSUE THREAD

**Issue by peterharperuk** [raspberrypi/pico-examples#461]
Make sure it works with USB
See https://github.com/raspberrypi/pico-sdk/issues/1603

**Comment by progvault** [comment]
I'm a little confused how the mutex works for stdio.  I added a comment to the discussion in https://github.com/raspberrypi/pico-sdk/issues/1603.

**Comment by arg08** [comment]
I've proposed a fix over on the other issue:
https://github.com/raspberrypi/pico-sdk/issues/1603#issuecomment-1963941166
