### ISSUE TITLE
What does example iperf.c

### ISSUE THREAD

**Issue by hasenradball** [raspberrypi/pico-examples#503]
@peterharperuk 
Dear Pi team,

sorry for the stupid Question what does the example picowiperf.c

It is as it is … no single line as a comment in the code!!!

**Comment by lurch** [comment]
See https://github.com/raspberrypi/pico-examples/blob/master/README.md#pico-w-networking and https://www.google.com/search?q=iperf

**Comment by hasenradball** [comment]
👍 thank you so much.

**Comment by hasenradball** [comment]
@lurch
I tested the code but is there any detailed description how it works?
Do I need two Picos for running the test???

**Comment by peterharperuk** [comment]
It's an iperf server. Just run an iperf client on another pc that can see it iperf -c <up address>
There is a way to build the code as a client. That's left as an exercise for the reader

**Comment by hasenradball** [comment]
@peterharperuk 

thank you understood.
A little comment in code (kind of abstract) would helb here.
:-)

**Comment by hasenradball** [comment]
@peterharperuk 

Just a short question.
Is it easy to build an PicoW code which can send an Http GET/POST Request every hour?

And is it possible to save data on the pico in a file.

For example read every 15 min. some sensor, but send it just every hour?

**Comment by lurch** [comment]
@hasenradball I feel like you're asking questions which ought to be asked on the forums https://forums.raspberrypi.com/viewforum.php?f=143
GitHub issues is used for tracking bugs.

**Comment by peterharperuk** [comment]
> Is it easy

Define easy

**Comment by hasenradball** [comment]
By usage of already available functions for
e.g.: http requests
etc…

**Comment by peterharperuk** [comment]
There's a http example here https://github.com/raspberrypi/pico-examples/pull/385

**Comment by hasenradball** [comment]
I just looked into the official examples.
Thanks.

**Comment by hasenradball** [comment]
One final question

in the wifi examples there are 2 executables

a bsakground version
and
a poll version

whats the difference?
