### ISSUE TITLE
 Modbus TCP client over Wifi for Raspberry Pi Pico W (RP2040)

### ISSUE THREAD

**Issue by francdoc** [raspberrypi/pico-examples#506]
Hi. I need help with this issue, if we achieve this then we can make a PR and contribute to **raspberrypi/pico-examples**.

Link to issue: **https://github.com/debevv/nanoMODBUS/issues/57**

Thanks in advance.

**Comment by lurch** [comment]
This sounds like a request better suited to the https://forums.raspberrypi.com/viewforum.php?f=143
