### ISSUE TITLE
Missing an example to set low power states on Pico 2

### ISSUE THREAD

**Issue by ullibak** [raspberrypi/pico-examples#530]
I try to enable the low power states on the Pico 2 but without any success. If I read the documentation correctly, power state P1.7 equals 1111 in binary or 15 decimal. Using 

```
uint32_t ps = 15;
int i = powman_set_power_state(ps);
```
returns 0 for i which means that the function was performed successfully, but adding

`printf("Power State: %d\n", powman_get_power_state ());`

right after the code above returns 0, so that somehow, the power state has not changed.

I am sure that I am missing something so it would be nice to add an example that demonstrates how the Pico 2 could be sent to a low power state for a definded amount of time.

Thanks!

**Comment by ullibak** [comment]
The sleep demo you mention uses some "tricks" to save power an I can not see how the new power management states of the RP2350 are used. Reading the specs of the RP2350 I and the SDK documentation, I was expecting some much more high level approach to send the RP2350 into an low power state. So a simple example in the SDK would be very helpful.

**Comment by peterharperuk** [comment]
Those sleep examples don't use powman. I don't think we're going to add a powman example. We want to add a new API for low power but ran out of time before the Pico 2 sdk update. In the meantime there are a couple powman examples here https://github.com/peterharperuk/pico-examples/commit/35db8fc31d322de2bcac641d9b6b0f6fdb73062c

**Comment by ullibak** [comment]
Hi
Thanks a lot! The powerman examples are really useful and helped a lot to undestand how to use the new power states.
With the timer example, I am able to lower the power consumption to 0.7 mA during sleep. This is good, but still a multiple of the values given in section 4.1.1 of the data sheet: 

https://datasheets.raspberrypi.com/pico/pico-2-datasheet.pdf

Power state P1.7 should draw only 0.148 mA.

In the data sheet they describe the current consumption measurements with

_All externally accessible GPIOs, SWD and SWCLK are unconnected. The RP2350’s USB PHY has been powered down,
and the DP and DM pull-downs enabled prior to entering the low power state. The USB cable remains connected to a
host computer._

I have no GPIO connected. But I do not know how to power down the USB PHY and how to enable the DP and DM pull-downs.

Does anyone know how to do this?

Thanks!

**Comment by lurch** [comment]
> But I do not know how to power down the USB PHY

That's probably related to section 6.1.4. in https://datasheets.raspberrypi.com/rp2350/rp2350-datasheet.pdf ? However note that it says "This supply must always be provided, even in applications where the USB PHY is never used."

**Comment by ullibak** [comment]
Thanks, lurch
Section 6.1. describes the different power supplies needed to run the RP2350 chip. But from the text in section 4.1.1. of the Pico 2 data sheet I conclude that there must be a way to power down USB PHY using a software command.

**Comment by peterharperuk** [comment]
I will try and find out where those numbers come from. The best I can achieve is .29mA, by powering the device with 3V3 and disconnecting everything (USB, UART, SWD) and removing R10 (at your own risk)

**Comment by ullibak** [comment]
I can get 0.36 mA when connecting a Li-Ion battery (4.2V) to VSYS and leave everything else disconnected. 

In section 1.2.2. of the RP2350 data sheet all the pins are described. The description for the USP_DM and USB_DP pins is:

_USB controller, supporting Full Speed device and Full/Low Speed host. A 27Ω series termination
resistor is required on each pin, but bus pullups and pulldowns are provided internally. These pins
can be used as software-controlled GPIOs, if USB is not required._

So there is a way to connect internal pulldowns via software commands. But I could not figure out how to to this.

**Comment by peterharperuk** [comment]
I can reproduce the power numbers in the datasheet with this commit. Make sure you disconnect everything except for 5v into vsys https://github.com/peterharperuk/pico-examples/commit/7dccd00d15ded4ddf961f44fdcd1f11a9d8c8be1

**Comment by tannewt** [comment]
> I can reproduce the power numbers in the datasheet with this commit. Make sure you disconnect everything except for 5v into vsys [peterharperuk@7dccd00](https://github.com/peterharperuk/pico-examples/commit/7dccd00d15ded4ddf961f44fdcd1f11a9d8c8be1)

Nice! How are others expected to reproduce this? Copy that code? Use a SDK API?

**Comment by ullibak** [comment]
Thanks a lot!
Li-Ion battery (4.11 V) connected to VSYS. Pico draws 150.8 microamps during low power. This is 620 microwatts. Great!!!

@tannewt: You find the code in https://github.com/peterharperuk/pico-examples/tree/35db8fc31d322de2bcac641d9b6b0f6fdb73062c/powman

it is emedded in the example directory tree there. You can copy th whole directory tree and substitute pico-examples.

I use a simplified standalone version, see attached zip file. 
[powman_standalone.zip](https://github.com/user-attachments/files/16885755/powman_standalone.zip)

copy these two files plus pico_sdk_import.cmake and pico_extras_import_optional.cmake from the Pico SDK into a directory and you should be able to compile as usual. I use VS Code with the Pico Extension.

**Comment by peterharperuk** [comment]
There might be a non-hardware API in future. So you can wait for that or else you'll have to copy that code.

**Comment by matsobdev** [comment]
Powering flash down will allow to save extra 10 uA (mileage may vary), but then when starting from flash, it should be powered back again: https://github.com/raspberrypi/pico-sdk/issues/2111

**Comment by pkolt** [comment]
Hi there! Has there been any progress on this topic? It’s been over a year since we last discussed it, and we still haven’t received an API (RP2350) for a standard transition into and out of deep sleep.

**Comment by r-bt** [comment]
Also curious if there have been any updates?

**Comment by tomealia1** [comment]
Using the powman timer example I am seeing current draw around 150uA.

Discussions seem to indicate that powering down flash and reducing vreg to 0.6 could bring that down to 50uA. I have not been successful in adding those steps to the powman timer example….has anyone else been able to add either of those steps?

**Comment by peterharperuk** [comment]
> I can reproduce the power numbers in the datasheet with this commit. Make sure you disconnect everything except for 5v into vsys https://github.com/peterharperuk/pico-examples/commit/7dccd00d15ded4ddf961f44fdcd1f11a9d8c8be1

**Comment by tomealia1** [comment]
> > I can reproduce the power numbers in the datasheet with this commit. Make sure you disconnect everything except for 5v into vsys [peterharperuk@7dccd00](https://github.com/peterharperuk/pico-examples/commit/7dccd00d15ded4ddf961f44fdcd1f11a9d8c8be1)

Do you mean the 150uA or the 50uA? Doesn’t that commit indicate 150uA?

**Comment by peterharperuk** [comment]
150uA. That's what this closed issue is discussing.
What "Discussions" are you referring to?

**Comment by tomealia1** [comment]
> 150uA. That's what this closed issue is discussing. What "Discussions" are you referring to?

There was a comment above about 
“Powering flash down will allow to save extra 10 uA (mileage may vary), but then when starting from flash, it should be powered up (or released from power down): https://github.com/raspberrypi/pico-sdk/issues/2111”

That’s where I saw the powering down flash…

Then there was this article….
https://gigazine.net/gsc_news/en/20240906-raspberry-pi-pico-2-power-saving

Where they indicated 57uA adding the vreg reduction using…

hw_write_masked(
&powman_hw->vreg_lp_entry,
POWMAN_PASSWORD_BITS | ((uint)VREG_VOLTAGE_0_60 << POWMAN_VREG_LP_ENTRY_VSEL_LSB),
POWMAN_PASSWORD_BITS | POWMAN_VREG_LP_ENTRY_VSEL_BITS
);
