### ISSUE TITLE
 pio quadrature_encoder example  not working on pico 2 RP2350

### ISSUE THREAD

**Issue by danielallstar** [raspberrypi/pico-examples#550]
The pio - quadrature_encoder example does not seem to work with the raspberry pi pico 2 (RP2350). It does however work with the pico RP2040.

The expected behaviour is that when you turn a quarature encoder the "new_value" changes. This does however not happen with the pico 2

Any help to resolve this issue would be appreciated

**Comment by lurch** [comment]
ping @pmarques-dev who originally wrote this example.

**Comment by pmarques-dev** [comment]
I haven't got a RP2350 yet, but have one ordered and shipping at the moment. When that arrives, I can test it and figure out what's going on

**Comment by peterharperuk** [comment]
I've reproduced the problem - checking what's going on.

**Comment by pmarques-dev** [comment]
from the top of my head, I would verify that the code is actually being successfully loaded at address 0. Maybe the new SDK uses PIO's for something and the example is silently failing to load the code and then trying to use it anyway

**Comment by Hax2022** [comment]
Le jeu. 19 sept. 2024 à 15:50, pmarques-dev ***@***.***> a
écrit :

**Comment by pmarques-dev** [comment]
if I remember correctly, to use the pins as inputs you don't have to multiplex them to the PIO, at least on the RP2040, so maybe there is a difference in behaviour there

**Comment by peterharperuk** [comment]
Yes - this is covered in the datasheet, section 9.3, it's a change from rp2040. Calling gpio_init also fixes the problem. I will submit a patch.

> The pad reset state is different from RP2040, which only disables digital inputs on GPIOs 26 through 29 (as of
version B2) and does not have isolation latches. Applications must enable the pad input (GPIO0.IE = 1) and disable
pad isolation latches (GPIO0.ISO = 0) before using the pads for digital I/O. The gpio_set_function() SDK function
performs these tasks automatically.

**Comment by pmarques-dev** [comment]
this in fact is in the SDK documentation, so it may need some clarification there as well:
https://www.raspberrypi.com/documentation/pico-sdk/hardware.html#group_hardware_pio_1gafa244b1be8f53a329db9d26298e054bb
"Note that this is not necessary for a state machine to be able to read the input value from a GPIO, but only for it to set the output value or output enable."

**Comment by peterharperuk** [comment]
Well arguably that's correct, you just need to have setup the gpio for input.

**Comment by danielallstar** [comment]
Thank you very much for looking into the problem and quickly finding a solution! 

I did a test and now the pio quadrature_encoder example works as expected on RP2350.
