### ISSUE TITLE
bootloaders/encrypted routines are not functioning properly

### ISSUE THREAD

**Issue by Octopus1633** [raspberrypi/pico-examples#552]
Hello, 

I successfully compiled the bootloaders/encrypted example and generated two firmwares: enc_bootloader.uf2 and hello_serial_enc.uf2. I dragged enc_bootloader.uf2 into the device first, and then dragged hello_serial_enc.uf2 into the device, but it seems that the encryption program did not run in the end. Is this normal? What is the problem?
![image](https://github.com/user-attachments/assets/c019b7ee-d4ff-4757-9010-9d7431071410)

**Comment by will-v-pi** [comment]
Did you write the generated otp.json file (in the build folder with the UF2s) to your OTP with `picotool otp load otp.json`? This example requires the AES key to be stored in OTP, else the decryption will not work - the generated otp.json file will write this key, lock the relevant OTP page, and enable secure boot on your device. I'll add this to the readme for this example

Note that writing the One-Time-Programable memory this way will only allow binaries signed with the private key used to run on your device.

**Comment by lurch** [comment]
So this issue can be closed?

**Comment by Octopus1633** [comment]
of course.
