### ISSUE TITLE
Question about the example ir_nec

### ISSUE THREAD

**Issue by michcfr** [raspberrypi/pico-examples#572]
Hello
My question is about the example /pio/ir_nec
What parameters should I change if I want the carrier to be at 15Mhz instead of 38Khz?

thank you

**Comment by lurch** [comment]
ping @mjcross who contributed this example in #129

**Comment by mjcross** [comment]
I'll take a look

**Comment by michcfr** [comment]
thank you. I would also change the transmission protocol.

**Comment by mjcross** [comment]
@michcfr asked: 

> What parameters should I change if I want the carrier to be at 15Mhz instead of 38Khz?

If you want to use a different carrier frequency, the relevant parameters are in the calls to `nec_carrier_burst_program_init()` and `nec_carrier_control_program_init()` in [nec_transmit_library/nec_transmit.c](https://github.com/raspberrypi/pico-examples/blob/master/pio/ir_nec/nec_transmit_library/nec_transmit.c).

**However** be aware that you will need to find (or construct) an IR receiver module that supports your chosen carrier frequency. The device used in the example (VS1838b) only supports 38 kHz. You might find others at up to 56 kHz but I think 15 MHz is rather unlikely.

**Comment by mjcross** [comment]
> I would also change the transmission protocol

That would certainly be outside the scope of this example.

**Comment by mjcross** [comment]
@lurch close?

**Comment by michcfr** [comment]
ok thank you very much
