### ISSUE TITLE
Cmake executable issue w/Pico-examples Projects

### ISSUE THREAD

**Issue by benji7480** [raspberrypi/pico-examples#575]
I was able to compile all the pico-examples Projects 2 months ago. Now i tried doing the same and the experience build errors.
I have copied text of the build Errors when building below:
build errors ---> Build failed: Unable to configure the project    Bad CMake executable: "". Check to make sure it is installed or the value of the "cmake.cmakePath" setting contains the correct path

 Let the debug begin for my issue
hope some one can quikly solve it
Note :file attach feature doesn,t work for me hence doing the copy text way

**Comment by benji7480** [comment]
one of the problems here is that i am attaching the files/snapshots of the error, but, not sure if it is showing on the issue page.....

**Comment by peterharperuk** [comment]
It's not. Can you not copy and paste the text?

**Comment by benji7480** [comment]
> It's not. Can you not copy and paste the text?

it a snapshot/jpeg file Bro

**Comment by benji7480** [comment]
> https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

Thanks Lurch for the hints, my files and all the limits are compliant, so my attached files shud be visible...One last thing i am using microsoft edge browser - is this browser supported or i shud use chrome,firfox,etc

**Comment by benji7480** [comment]
i have resorted to text copy way as file attach doesnt work as peterharperuk suggested. Let the debug begin for my issue
hope some one can quikly solve it
