### ISSUE TITLE
Missing example for C++ HTTPS server

### ISSUE THREAD

**Issue by qubit999** [raspberrypi/pico-examples#589]
I already have a C++ HTTP Server backend supporting GET/POST requests with CGI, SSI and a lightweight filesystem but how do I enable HTTPS support? Is there an example?

**Comment by peterharperuk** [comment]
There's are tls_client and http_client examples that use tls.

**Comment by qubit999** [comment]
Ok, but is there an example for http(S) server?

You might think there's information on Google but there is none:
https://www.google.com/search?q=pico+sdk+https+server

I am building this project: https://github.com/qubit999/senfOS and I want to extend the http server with https.
