### ISSUE TITLE
VS Code: Launching of gdb-multiarch not possible

### ISSUE THREAD

**Issue by schnappviech** [raspberrypi/pico-examples#8]
When setting a Raspberry Pi up as described in the Getting Started guide, two problems arise when launching the debugger:

- Setting "gdbpath" in launch.json is marked as not allowed
- When launching the setting is ignored, and arm-none-eabi-gdb is used, which is unavailable

It seems that setting "cortex-debug.gdbpath" can only be set in settings.json

**Comment by edstevo** [comment]
Hi schnappviech. Please can you confirm the values for "cortex-debug.gdbpath" and or "cortex-debug.armToolchainPath"?

I am trying to launch the debugger, but am faced with the error:

"OpenOCD GDB executable "arm-none-eabi-gdb" was not found. Please configure "cortex-debug.armToolchainPath" correctly."

Thank you

**Comment by schnappviech** [comment]
That is the same error I also got.

cortex-debug.armToolchainPath tells VS Code where to look for "arm-none-eabi-gdb", while cortex-debug.gdbPath specifies the name of the executable too.

Applying PR #9 did the trick for me. It requires gdb-multiarch to be in PATH though.

**Comment by edstevo** [comment]
Oh man - I've been attacking this all day!!! Thank you so much. You're a _blinking_ legend!

**Comment by lurch** [comment]
Fixed by #16
